### ISSUE TITLE
Redundant SetUnviewed call in BaseProfilerProvider.SaveProfiler?

### ISSUE THREAD

**Issue by AkosLukacs** [MiniProfiler/dotnet#111]
Hi!

At https://github.com/MiniProfiler/dotnet/blob/master/StackExchange.Profiling/BaseProfilerProvider.cs#L86
the SaveProfiler calls `storage.SetUnviewed()` right after saving it the first time.

Is that just a redundant update call to the storage, or something I missed? (it does a sql update, with SqlServer storage, checked with sql profiler)

**Comment by yellis** [comment]
And right before the call, `HasUserViewed` is already set to 0? I am thinking that this was originally put in because there might be some storage implementations which need to have Unviewed explicitly set.

**Comment by NickCraver** [comment]
Clearing up: this isn't redundant because how it's unviewed can vary by provider. For example, if storing in Redis, this likely adds it to a list or set. But, that still means providers like SQL Server aren't optimal, as they're making an extra query.

I've fixed this in https://github.com/MiniProfiler/dotnet/commit/30f771b52dc66d5fe20706f6a352802c281175ee by adding `IAsyncStorage.SetUnviewedAfterSave`, which allows each provider to indicate if they want this call or not. I could have said "each provider's `Save(Async)()` should just call this internally, but I think that's less intuitive overall.

Even if this moves, I'll keep it optimized in V4, so closing this out to cleanup.

**Comment by AkosLukacs** [comment]
Thanks for the clarification! It's good to see activity again, MiniProfiler is awesome!
