### ISSUE TITLE
Causes user session to never expire when using FormsAuthentication.SlidingExpiration

### ISSUE THREAD

**Issue by ajbeaven** [MiniProfiler/dotnet#117]
I'm using standard .NET FormsAuthentication to authenticate the users on my site with the following configuration:

```
<system.web>
  <authentication mode="Forms">
    <forms loginUrl="~/account/login" timeout="30" slidingExpiration="true" />
  </authentication>
</system.web>
```

SlidingExpiration causes the forms authentication cookie and ticket to be renewed if a request is made after half the time of the timeout, effectively causing the user to be timed out only if they are inactive. 

MiniProfiler seems to cause the cookie and ticket to continually be renewed such that a user will never be logged out. 

The same problem occurs when you've got frequent ajax polling, however this can be solved fairly easily by simply [removing the forms authentication cookie](http://stackoverflow.com/questions/14518294/skip-renewticketifold-during-ajax-call-to-a-specific-action) on those requests like so:

```
Response.Cookies.Remove(FormsAuthentication.FormsCookieName)
```

Sorry, I would do a pull request for this but I have very limited experience with developing handlers so am unsure where this code might be added.

**Comment by NickCraver** [comment]
MiniProfiler doesn't make requests by itself (other than *immediately* after the page loads)...so are there other AJAX requests happening that are being profiled? If that's the case, those should probably be excluded from profiling, since my guess would be *those* are excluded from expiration extensions but the resulting profiler requests are not.

**Comment by ajbeaven** [comment]
You're right, this is likely caused by the profiled AJAX requests. Of course, stopping the profiling would fix the issue with slidingExpiration but I was hoping I'd be able to use them both.

**Comment by NickCraver** [comment]
@ajbeaven If you want MiniProfiler to not function on those specific requests, the fix would be to throw away the profiler so that no follow-up request is made to get the results (since the MiniProfiler headers won't be on the responses), like this:
```c#
MiniProfiler.Stop(true);
```

Closing this out to cleanup, but happy to help further if that doesn't cover it!
