### ISSUE TITLE
Results-Index page does not show timestamps

### ISSUE THREAD

**Issue by cmaart** [MiniProfiler/dotnet#128]
The results-index page does not show any timestamps. Only duration.
My guess is that the template can't handle the sent DateTime-Format which is sent in the following format:
`Started
:
"/Date(1462782157890)/"`

![image](https://cloud.githubusercontent.com/assets/4008452/15107599/ecb68676-15d0-11e6-8c23-2214869500c3.png)

![image](https://cloud.githubusercontent.com/assets/4008452/15107641/2f617d1e-15d1-11e6-81c2-fa66a3e67716.png)

**Comment by NickCraver** [comment]
TODO: Check this in vNext with current UI bits.

**Comment by NickCraver** [comment]
This is fixed in the upcoming v4 release, thanks for the report! Here's a view (Client Timing will show properly when present, e.g. page views):

<img width="933" alt="screen shot 2017-01-14 at 14 19 59" src="https://cloud.githubusercontent.com/assets/454813/21957465/9e28ea36-da64-11e6-9065-920a69baf701.png">
