### ISSUE TITLE
Showing Duplicate Libs/calls

### ISSUE THREAD

**Issue by weedkiller** [MiniProfiler/dotnet#148]
Hi, currently it shows the queries, would be nice it could show duplicate includes (JS/CSS) as well - similar to ..

![image](https://cloud.githubusercontent.com/assets/21086190/22532521/8e3926c2-e8b5-11e6-871c-4a1fa0576591.png)

Also do you have ASP MVC 5 updates targeting 4.52 or 4.61, seems like the code is old

thanks

**Comment by NickCraver** [comment]
Duplicate includes is harder (and not really a performance thing *per se*, as that's depend on the content of the includes). For ASP.NET 5, you can track progress on the V4 branch here: https://github.com/MiniProfiler/dotnet/issues/144

I've got a lot of house stuff happening at the moment (finishing a basement), but hope to wrap up a lot more items soon.

**Comment by NickCraver** [comment]
There's an alpha of v4 up on NuGet: https://www.nuget.org/packages?q=Miniprofiler.AspNetCore but I don't think we can reasonably include what you're asking for on the dupes. It's not really a profiling thing anyway, and a dupe (like in profiling) is also not necessarily a problem or a solution either way (due to running twice with overrides, etc.)

This is client-side analysis looking at the page, and even that would be unreliable. For example, what if part of the page loads later, or was via AJAX? You'd be scanning potentially very large pages for their includes and reasoning in a way that only lends itself to questionable conclusions at best :-/

**Comment by weedkiller** [comment]
I guess that makes sense, but to start with - having a check at the very least, for e.g. during the dom load complete or something similar would be greatly helpful just my .02c

**Comment by NickCraver** [comment]
@weedkiller I appreciate the thoughts for sure - I just think MiniProfiler isn't the right place for this. It's trying to foremost profile the server, and the problem here is many false positives in such an alert. If we can't reasonably discern something actionable for users, it' a cry-wolf scenario that's better not to alert at all on.
