### ISSUE TITLE
Page 'results' disappears on mouse click outside the list

### ISSUE THREAD

**Issue by darkurse** [MiniProfiler/dotnet#164]
First of all thank you for this great tool. It's saving us so much time and pain. Now this `issue` is more an annoyance than a proper issue.

**Running :**  http://localhost:12345/profiler/results?id=50a3c15a-dc0d-4531-9dd8-ebebdc4f10c4
**Issue :**  Click anywhere on the page but the list.
**version :**  4.0.0-alpha24
**Note :** I'm using the MiniProfiler on a ASP.NET Core app

**Side note :**

I had another issue all day long yesterday but I cannot reproduce it today so I won't log a proper issue.  Yesterday, `/profiler/results` page was very long to load ( between 5 and 10 seconds ). Server app was not under stress, all other pages on the server were very fast. Restarting the server app wasn't helping. Even a computer restart didn't help..

**Comment by darkurse** [comment]
Regarding the `/profiler/results` page slowness, it happened again. The more you run the MiniProfiler the slower it gets. I am not doing anything special with it. Just calling two different actions on a controller all day long to improve performance here and there in the code.
So the more I use it in the day, the longer the controller takes to reply.

**Comment by NickCraver** [comment]
@darkurse I'll be switching how we profile ASP.NET Core to be even more lightweight - if you can readily reproduce this that's awesome. Let me get a refactor in and ping you to try a new alpha if you don't mind. That'd be awesome, since I can't repro easily in any small application and Stack Overflow apps are still far from adopting Core.

**Comment by jdaigle** [comment]
Looking at the changes between v3 and v4 for [includes.js](https://github.com/MiniProfiler/dotnet/blob/3fb3d177852499139311e0fa150dc87c53dccf02/src/MiniProfiler.Shared/ui/includes.js), it seems the culprit is the `bindDocumentEvents` function. This hooks up a handler on `$(document)` which hides the "provider-popup" on escape or clicking outside the "popup".

In v3 `bindDocumentEvents` was only called from `initPopupView`. In v4 it's called from the main `init` function.

**Comment by NickCraver** [comment]
Thanks yet again @jdaigle - that's exactly it. It'll be fixed in the next build and available on MyGet in a few minutes.
