### ISSUE TITLE
Add handler config to NuGet package

### ISSUE THREAD

**Issue by tomascassidy** [MiniProfiler/dotnet#199]
In addition to using the new `WebRequestProfilerProvider.Setup()` method, I had to manually add the handler below for `~/profiler` into `Web.config`.

It's not documented anywhere and is not added automatically by the NuGet package.  Can this be documented and added to the NuGet package so it's added to `Web.config` on package install?

```xml
  <system.webServer>
    <handlers>
      <add name="MiniProfiler"
           path="profiler/*"
           verb="*"
           type="System.Web.Routing.UrlRoutingModule"
           resourceType="Unspecified"
           preCondition="integratedMode" />
    </handlers>
  </system.webServer>
```

If this isn't required, then there's something else going wrong somewhere.

**Comment by NickCraver** [comment]
This isn't necessary since it's registered during setup as a route. Can you show me your setup and where it lives? Is there anything abnormal about your routing?

**Comment by jdaigle** [comment]
I believe this is required if `runAllManagedModulesForAllRequests="false"` for the `<modules>` section in `<system.webServer>`. We have an app where that is the case; it requires manually registering the handler just like this - although I'm still not precisely sure why.

But I think that `runAllManagedModulesForAllRequests="false"` is hopefully uncommon enough these days. While it might be useful to put in the documentation, it's probably not worth adding it to the web.config by default.

**Comment by jdaigle** [comment]
Did some digging. The issue seems to be that the "static" resources (`includes.js` and `includes.css`) are mapped to the `StaticFile` handler instead of being handle by UrlRouting. I think that when `runAllManagedModulesForAllRequests="false"`, only "extensionless" URLs are picked up by UrlRouting. If the path ends with what looks like a file extension, or even just a single `.`, then its treated as a StaticFile unless there is some other handler mapping.

![image](https://user-images.githubusercontent.com/104650/29073728-acfd1e62-7c1a-11e7-8ad0-ec54a1c30932.png)

Also I was slightly wrong about `runAllManagedModulesForAllRequests="false"` in that there are legitimate performance reasons to keep it off (i.e. serving static files from disk).

**Comment by tomascassidy** [comment]
Looks like ```runAllManagedModulesForAllRequests``` is the culprit here.  The default MVC5 Web Application template I'm using from VS2015 doesn't specify any value for ```runAllManagedModulesForAllRequests``` in ```Web.config``` and I didn't notice that it defaults to ```false```.  Can you add something to the docs to specify that ```runAllManagedModulesForAllRequests``` needs to be set to ```true``` for this to run automagically?

**Comment by NickCraver** [comment]
As of MiniProfielr v4, the `web.config` handler is no longer needed. Finally closing this out to tidy up :)
