### ISSUE TITLE
Why is UrlRoutingModule registered under <handlers>?

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#226]
The basic troubleshooting section on MiniProfiler's site includes the following snippet:

    <handlers>
        <add name="MiniProfiler" path="mini-profiler-resources/*" verb="*" type="System.Web.Routing.UrlRoutingModule" resourceType="Unspecified" preCondition="integratedMode" />
    </handlers>

Why are we registering a module as a handler here? It works, but it seems wrong... Shouldn't it be placed in `<modules>` instead?

**Comment by NickCraver** [comment]
@Which version of MiniProfiler are you on? I've just made registration automatic in the latest MyGet (testing for a day or two then we'll push to NuGet) so that just calling `MiniProfiler.Configure(options);` in code will register everything, web.config shouldn't need to be touched at all :)

**Comment by rlenders** [comment]
Right now I'm using 4.0.0-alpha6-83. When I'll update to the latest version, I'll check and see what happens if I remove the handler from my Web.config.

Nonetheless, the documentation on MiniProfiler 3 includes the snippet I posted above. And I remember needing it in my Web.config when I was using the latest stable (3.2.0.157). My question still stands, why would you register a module as a handler? That's invalid configuration, isn't it? Why does it work though?

I'm asking because I want to learn more about modules and handlers in ASP.NET.

**Comment by NickCraver** [comment]
@rlenders Honestly it's been so long I'm not sure, and given the other things on the plate, no time to dig into the why at the moment. If you find anything interesting I am just as curious, but currently severely strapped for time.

**Comment by NickCraver** [comment]
This can be verified in the samples - no web.config entries are needed anymore :)

**Comment by lorenpaulsen** [comment]
It took some digging to find this, but the reason the sample works without adding the handler manually is that the sample includes the following in its web.config:

```xml
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
  </system.webServer>
```

The attribute `runAllManagedModulesForAllRequests=true` is not included by default, at least not anymore (I just tried creating a new MVC5 web application to see what the default `web.config` looks like now), so this would have to be added.
