### ISSUE TITLE
Disable mini profiler in production (not hide)

### ISSUE THREAD

**Issue by dalibor983** [MiniProfiler/dotnet#232]
How to totally disable mini profiler in production environment?
I'm using dotnet core 2.0.

**Comment by StuffOfInterest** [comment]
I use a helper class that wraps all of the external calls to MiniProfiler.  Any place that would call something like "MiniProfiler.Start()" or "MiniProfiler.RenderIncludes()" instead calls "MyHelper.Start()" or "MyHelper.RenderIncludes()".  This helper checks for an app configuration key defined in the web.config file  and if the value is not set to true it exits all of the methods immediately.  Add in a little magic to store the conditional into a static variable and you have almost no run-time overhead to pass through the calls.  If Web.Config is not a good option, then conditional compiler attribute could be used ('[Conditional("DEBUG")]') in the helper class so that those methods don't get called at all in non-debug environments.

**Comment by NickCraver** [comment]
Closing this out barring any new info, I think answers here are good since there's only really a few "don't call that" ways to go.
