### ISSUE TITLE
Update dependent packages to latest .net standard versions.

### ISSUE THREAD

**Issue by atodd-geoplan** [MiniProfiler/dotnet#299]
And related binaries...

System.Diagnostics.DiagnosticSource (4.5)
Microsoft.EntityFrameworkCore.Relational (2.1)
Microsoft.Extensions.Logging.Abstractions (2.1)

Save adding dependent assemblies

**Comment by NickCraver** [comment]
Is something not working in `netcoreapp2.1` currently? If so, I want to address it!

With libraries we want to target the widest audience, for instance: we wouldn't want to force everyone to upgrade to 2.1 in order to use MiniProfiler.

**Comment by StuffOfInterest** [comment]
I'm using MiniProfiler 4 in a ASP.NET Core 2.1 application.  I do get a couple of odd NuGet warnings regarding resolving package dependency versions during "dotnet restore" on my build server, but I think that is an issue with the package dependency resolver and not with MiniProfiler.  

My situation is more complex than a basic app in that I have a support library targeting .NET Standard 2.0 which consumes MiniProfiler, Entity Framework, and some pieces of ASP. NET Core.  That support library is then consumed by a ASP.NET Core 2.1 app.  

All three of the dependencies above show up in the dependency tree in Visual Studio under "MiniProfiler.EntityFrameworkCore".

If I had to hazard a guess, I think the original poster may have some parts of his app targeting 2.0 and others targeting 2.1.

**Comment by atodd-geoplan** [comment]
netcore 2.1 brought in the dependencies mentioned above, but mini profiler is currently pulling in older versions of these binaries.

would just be easier to update the packages at the source of truth (mini profiler's packages.config)

**Comment by StuffOfInterest** [comment]
I'm not following on this.  If MiniProfiler is updated to depend on version 2.1 then it will no longer support version 2.0.  If you have other code in the web project already referencing the version 2.1 assemblies then MiniProfiler will use them.  A library will typically target the lowest required version to avoid locking out apps that have not been updated.

**Comment by atodd-geoplan** [comment]
We are up to date with all our packages. All our code libraries target 2.1 core or 2.0.3 standard.

However, I have missed a vital piece of info (apologies). The presentation layer is still MVC5.

`install-package miniprofiler.mvc5`

does not pull in the latest (not existing in project) standard dependencies, hence my post.

I just tried from a vanilla mvc5 project. It pulls in e.g. _Microsoft.*.*.Abstractions_ 2.0.0 not 2.1.0

**Comment by StuffOfInterest** [comment]
Let me see if I understand this right, are you running MVC 5 on top of a .NET Core 2.1 application?  I didn't know that was possible OK, my experience doesn't apply here as I'm using MiniProfiler on an ASP.NET Core 2.1 application with the MiniProfiler.AspNetCore.Mvc package.

**Comment by atodd-geoplan** [comment]
Nope

We have 1 legacy mvc web application (framework 4.7.1) referencing a number of .net standard code libraries. So actually the title of the post should be update to latest .net standard packages. I will update it.

We also have a number of .net core console applications that run under aws batch that talk to those same code libraries (its a dll-based application services tier -  all of our code is internal).

**Comment by NickCraver** [comment]
@atodd-geoplan If MiniProfiler upgraded, it'd become unusable for anyone not on latest. That's not good behavior for any library. It works fine on *either* (and many more versions to come), a user is free to use updated versions of the underpinning libraries, or not. MiniProfiler doesn't *need* the latest version for any reason, so upgrading dependencies when not needed is just hostile to the user base, and prevents MiniProfiler enhancements that do not depend on new libraries underneath from reaching the widest user base.

To be clear, this is MiniProfiler specific at all - it's how most libraries are supposed to behave. You should only upgrade a library dependency in a few situations:
- You need it for new functionality
- Breaking changes
- You need to assist that library in getting out, e.g. a security fix in the dependency

...otherwise, we're just narrowing who gets the latest to who's on the latest *everything*. As an illustration, let's turn the tables. Let's say .NET Core 2.2 was out tomorrow, and I upgraded. But you're not ready. I didn't *need* to, I just felt like it. I added cool new features that didn't *need* those library updates, but because I felt like it, you can't get them until you can upgrade your entire application. That kinda sucks, right? It's not fun to be on the other end of such a change. Hope that helps a bit in explaining why libraries don't behave this way.

**Comment by atodd-geoplan** [comment]
I would check the dependencies chart for previous versions and take the one that suits my project.

Is the whole point of versioning.

**Comment by NickCraver** [comment]
> I would check the dependencies chart for previous versions and take the one that suits my project.

Yes, absolutely. You're totally right. That's your choice and I support you upgrading. I'm all for it. But that's not what you're asking here. You're asking me to make that decision for *everyone* using MiniProfiler, not to use the ones that suit their project. If they can't get approval to upgrade, can't find time to test/validate/etc., they're out of luck and we're needlessly hosing them. That's what I mean by being hostile to users. There's *zero* reason to take on the latest dependencies and a lot of downsides to doing so. Again: this is how every library is *supposed* to behave. As an example, go look at NuGet for the libraries you listed. They don't depend on the latest version of their dependencies either, for all the reasons I've given here and more.

Addressing `netstandard`: `netstandard` is not the same thing here. Though it's related, none of the library dependencies you're talking about here are part of the standard, they are built upon it, as is MiniProfiler.
