### ISSUE TITLE
Using MiniProfiler without Razor (ASP.NET Core)

### ISSUE THREAD

**Issue by SoaresMG** [MiniProfiler/dotnet#307]
Hi,

I've used this on several projects and I really like it.
I'm developing an web application using a server side built with ASPNET Core (API) and the UI is made purely with javascript (React), both sides are totally independent.

Is it possible to load the javascript and css in my UI, connecting it to the server-side to retrieve the data?

It would probably work, IF this package wouldn't rely on things like ViewData, ViewBag or Model and instead consume a request that retrieves the data.

Is there anyway to do it right now? 

If not, I'm going to create a project that will get from the server (using a fetch library) all the info do be displayed.

**Comment by NickCraver** [comment]
Yes, it's possible indeed. MiniProfiler isn't really using all those bits unless *you* are. We use them tag tag helpers, but that's just *for tag helpers*.

The overall premise is: a MiniProfiler runs, it has a GUID, that GUID is on a response header. The fetch for the data for that GUID is already a client-side request (it has to be, because the profiler isn't complete at the time the ID is sent to the client...but we do know the ID). If you try the sample apps, you'll see this after-the-page-load fetch. We already support most AJAX frameworks out of the box, but you can see the `MiniProfiler` page object to trigger anything you'd like as well, including loading results (in case you want to relay the IDs in some other way).

Here's an example:
```js
MiniProfiler.fetchResults(["myguidhere","anotherguidifyouwant!"]);
```

**Comment by NickCraver** [comment]
Closing this out to cleanup!
