### ISSUE TITLE
WrappedView breaks access to RazorView in ViewLocationExpander

### ISSUE THREAD

**Issue by PTwr** [MiniProfiler/dotnet#322]
In custom `IViewLocationExpander` I need to access `RazorView` from `(ViewLocationExpander.ActionContext as ViewContext).View as RazorView`. 

For now I "fixed" it with Reflection, `.GetType()?.GetField("_wrapped", BindingFlags.Instance | BindingFlags.NonPublic)`, but some civilized way would be nice.

`WrappedView` is currently `Internal` and wrapped `IView` is private. So I tried to provide my own implementation. However it must be provided via my own `ProfilingViewEngine` (which is public while sitting in `Internal` namespace), which in turn is provided in `Configure` hidden in internal classes underneath innocent looking `AddMiniProfiler` so replacing viewEngine requires building configuration from scratch. Which made reflection look like reasonable choice.

Is this blocked by design or for no apparent reason?

**Comment by NickCraver** [comment]
You can see #162 for some details here. It's not intentionally blocked and I'd rather we not have this layer at all, but the current state of DiagnosticSource in ASP.NET MVC (no concrete or exposed types) is a nightmare to consume. I've asked (and gotten) the events fixed in https://github.com/aspnet/Mvc/issues/6222, but [the types are still anonymous and not exposed](https://github.com/aspnet/Mvc/blob/2.2.0-preview2/src/Microsoft.AspNetCore.Mvc.ViewFeatures/Internal/MvcViewFeaturesDiagnosticSourceExtensions.cs#L23-L28). In short, they're terrible for consumption or profiling.

For context, I've discussed this quite a bit with the team that owns the diagnostic bits (though no one "owns" it overall...and that's the problem, IMO). Lots of context in the StackExchange.Redis discussion here: https://github.com/StackExchange/StackExchange.Redis/issues/833

Application Insights, Microsoft's own platform, *doesn't use these*. The diagnostic events have no first class consumer and as a result they don't seem to get prioritized. I'm really hoping the .NET teams will change the behavior here and make a usable API. [I really did try to push for this](https://github.com/dotnet/corefx/issues/18114), but [gave up](https://github.com/dotnet/corefx/issues/18114#issuecomment-322345786). The Entity Framework team has a great example of fixing this to what it should be in a consumable API, see https://github.com/aspnet/EntityFrameworkCore/pull/8351. As a result, [MiniProfiler's observer can be quite reasonable](https://github.com/MiniProfiler/dotnet/blob/cc91adf5997c09344c5102500b8e120132ee51be/src/MiniProfiler.EntityFrameworkCore/RelationalDiagnosticListener.cs) on top of those diagnostic messages.

cc @DamianEdwards - can we please, please look at making DiagnosticSource usable in ASP.NET v3? Like the Entity Framework team did?

**Comment by NickCraver** [comment]
Since concrete types are now in - this is unblocked! I'm working on it over in #475.
