### ISSUE TITLE
EF6 case as simple as possible

### ISSUE THREAD

**Issue by okarpov** [MiniProfiler/dotnet#330]
@josh @NZKoz @vangberg @rtomayko 
I need to profile EF6 only inside of single controller action only.

What are the simplest and easiest steps to set-up and initialize EF6 miniprofiler, profile the EF6 performance inside a single controller action and render profiling info onto its view?

(no need for SQLite or any other db-like storage, in-memory just fine to render result on to view and dispose everything)

Thank you.

**Comment by NickCraver** [comment]
Can you elaborate on what you're trying to do? For example, do you want to profile everywhere, but only EF6 in one spot? Or only profile (including EF6) in the one spot, with no MiniProfiler anywhere else? Or some other setup?

**Comment by okarpov** [comment]
@NickCraver something like "Only profile EF6 in the one spot with no MiniProfiler anywhere"

**Comment by NickCraver** [comment]
I'm not sure that approach is possible since we need to hook up to a global piece of EF6 when configuring the first time (and before first usage). You could hook up with it inactive (very minimal overhead) and only activate profiling on that route with a manual start/stop, though. It's possible @jdaigle has some ideas I'm not thinking of here though...

**Comment by jdaigle** [comment]
I don’t think that there is any getting around the global EF config to support MiniProfiler. But it is very low overhead, almost nonexistent, when the profiler isn’t active.

Once configured, you can just call Start/Stop from any controller action (but I would recommend creating an action filter to encapsulate and make reusable), instead of BeginRequest/EndRequest .

**Comment by NickCraver** [comment]
Approach for this is listed above, so closing this one out :)
