### ISSUE TITLE
NuGet packages are unlisted for MiniProfiler.Providers.MongoDB

### ISSUE THREAD

**Issue by Turnerj** [MiniProfiler/dotnet#348]
I noticed in the readme all the badges for `MiniProfiler.Providers.MongoDB` appear broken:
![image](https://user-images.githubusercontent.com/904226/49800961-c2a30d00-fd40-11e8-96fb-c10946c603c4.png)

Seems that all versions of the package are unlisted on NuGet: https://www.nuget.org/packages/MiniProfiler.Providers.MongoDB/

Not sure if that was intentional or not so thought I'd raise an issue about it.

**Comment by NickCraver** [comment]
Yep - it's intentional...the problem is MiniProfiler is strongly named, and the MongoDB providers are not. While the code is prepped, we can't ship a package until they start signing. The NuGet.org reservation is in hopes that'll change but...I'm not sure if/when they'll change the stance there. The official recommendations have changed to signing recently, for what it's worth.
