### ISSUE TITLE
Timing.Children is not threadsafe. 

### ISSUE THREAD

**Issue by yellis** [MiniProfiler/dotnet#35]
See [related thread on the community site](http://community.miniprofiler.com/t/timing-class-is-not-threadsafe/30?u=yaakov_ellis).

Want to make interactions with `Timing.Children` threadsafe.

**Comment by alexsku** [comment]
I think I've run into the Children concurrency issue using MiniProfiler V4. This is a PR illustrating the issue (based on V4 MVC sample): https://github.com/alexsku/dotnet/pull/4

In my case I have multiple async tasks executing and awaited by the calling thread all together (using Task.WhenAll). Each task is using await with ConfigureAwait(false) (a typical pattern for a service layer in a web application). Because of the ConfigureAwait(false) the continuations for the tasks will be executed in parallel causing the concurrency issue.

I think using lock is a good way to solve the concurrency issue. Here is my PR that is addressing it (among other things): https://github.com/MiniProfiler/dotnet/pull/147 (the PR is for V4 of MiniProfiler). 

I think lock's performance is pretty good when there is low contention (which i think is the case with MiniProfiler usages, otherwise this issue would be very high priority). Here is a small test where lock is measured against other synchronization primitives: https://github.com/alexsku/dotnet/pull/5 when the lock is not contended. 

Btw, I think V4 fixes the issue described by @dixon above by using AsyncLocal

**Comment by NickCraver** [comment]
Fixed by 9ec58fa5a323c7c4b10a07deb615afdcfaed8abd
