### ISSUE TITLE
MiniProfilerOptions.ResultsAuthorize and ResultsListAuthorize are not async

### ISSUE THREAD

**Issue by metoule** [MiniProfiler/dotnet#354]
To properly check who can access the profiler results, I first need to authenticate the user, but the authentication API is async. That means I have to block the call in `ResultsAuthorize`, for example:

```C#
    services.AddMiniProfiler(options =>
    {
        options.RouteBasePath = "/profiler";
        options.ResultsAuthorize = request =>
        {
            var context = request.HttpContext;

            // --> here, I'd like to write await context.AuthenticateAsync()
            var authResult = context.AuthenticateAsync().Result;
            if (!authResult.Succeeded)
                return false;

            var claimsPrincipal = authResult.Principal;
            return claimsPrincipal.IsInRole("ProfilerContributor");
        };
    })
```

Do you think you could add an async version `Func<HttpRequest, Task<bool>>`? Or is there a better way to authenticate a user first?

**Comment by NickCraver** [comment]
If you put your authentication before MiniProfiler, you can access that in the handlers (given you have access to those injected things where MiniProfiler is configured). To do this, you'd ensure authentication always happens and something is set indicating who the user is. Presumably, you don't need to `async` authenticate the user on every call - just before this one.

I can take a look at if these can be async, but I don't think they can be since they're called in a few synchronous paths (at least in ASP.NET MVC - Core *maybe* but I'll have to dig).

**Comment by metoule** [comment]
I managed to access the `ClaimsPrincipal` by putting my authentication before MiniProfilier, so I no longer need to call the `AuthenticateAsync` method. Thanks!

**Comment by NickCraver** [comment]
@metoule awesome - thanks for the update!
