### ISSUE TITLE
Feature suggestion: Profiling HttpClient calls using DiagnosticSource

### ISSUE THREAD

**Issue by mcintyre321** [MiniProfiler/dotnet#357]
It should be possible to automatically profile all HttpClient calls using DiagnosticSource - https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/HttpDiagnosticsGuide.md

If I get a free evening sometime soon, I'll give it a go. But if not, maybe someone else will have a go at it!

**Comment by NickCraver** [comment]
I looked into how they're doing things, but unfortunately no progress has been made here. I've been looking at DiagnosticSource for some time, but it has a lot of issues. See https://github.com/StackExchange/StackExchange.Redis/issues/833 for a *long* discussion on this between the Microsoft team, others, and I.

In the case of HttpClient, I thought *maybe* they fixed something but...nope.

- The names of their types are still internal: [DiagnosticsHandlerLoggingStrings.cs#L12](https://github.com/dotnet/corefx/blob/ec7a4c6e09d655421195580b7eea887000afc367/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandlerLoggingStrings.cs#L12)
- The types are still anonymous: [DiagnosticsHandler.cs#L144-L150](https://github.com/dotnet/corefx/blob/ec7a4c6e09d655421195580b7eea887000afc367/src/System.Net.Http/src/System/Net/Http/DiagnosticsHandler.cs#L144-L150)

Unfortunately, *nothing* has gotten better since #833. I keep getting my hopes up, because the current API is *so fixable*. but as long as Microsoft doesn't care, here we are. If something changes here, I'm happy to look into it again. I sincerely hope they treat this API better than it is today, it has so much potential. But as long as no one agrees, few downstream can benefit from the chaos that is DiagnosticSource.

I really am sorry that's the answer, I too get sad whenever I dig into this.
