### ISSUE TITLE
Console Dot Net core getting started guide is unclear

### ISSUE THREAD

**Issue by roa-nyx** [MiniProfiler/dotnet#363]
https://miniprofiler.com/dotnet/ConsoleDotNetCore

There are two console examples one for ConsoleDotNet and another for ConsoleDotNetCore. One instructs you to install `MiniProfiler` and the DotNetCore instructs you to install `MiniProfiler.AspNetCore`.

I feel like either this is a mistake? Or if it's not that it needs to be explicitly called out as to why for DotNetCore you need to use a package labeled for AspNet in a console application.

**Comment by NickCraver** [comment]
The example is correct - there is no .NET Core packages (because it's just too many packages). You *could* use `MiniProfiler.Shared` and do some manual bits, but thus far profiling console applications is rare enough that another package of packages and dependencies between `.Shared` and `.AspNetCore` isn't really warranted.

For what it's worth, `MiniProfiler` simple pre-dates .NET Core by many years. If it didn't exist back then, it'd have been called `MiniProfiler.AspNet` today. It retains the `MiniProfiler` name for ease of user upgrades. It is an ASP.NET with those bits just like `MiniProfiler.AspNetCore` is, though.

**Comment by klick-barakgall** [comment]
Gotcha. Do you think it maybe it'd be good to have that explicitly called out in the .net core example? That even though it's a console example you still need to reference the `AspNetCore` package?

**Comment by NickCraver** [comment]
Yeah sure, if that would help clarify things I'm all for it...that's the entire point of the samples after all :)
