### ISSUE TITLE
MiniProfiler.Providers.Redis target StackExchange.Redis

### ISSUE THREAD

**Issue by pergardebrink** [MiniProfiler/dotnet#366]
I see that the MiniProfiler.Providers.Redis is having a dependency on StackExchange.Redis.StrongName >=1.2.6. 

Is there a plan to change the dependency to StackExchange.Redis, now that the 2.0 version is strongly signed? Or will that not happen until MiniProfiler 5.x (maybe considered a breaking change)?

**Comment by NickCraver** [comment]
Talked to @mgravell about this - my plan is to wait until we're doing Dapper v2 (since this is a breaking change) and eat the `StackExchange.Redis.StrongName` v1.x => `StackExchange.Redis` v2.x and `Dapper.StrongName` v1.x => `Dapper` v2.x at the same time. In both cases, we're dropping the .StrongName assembly and strong naming the main library to simplify things for everyone and eliminate a lot of pain and questions around the whole deal. After that, yeah it'll be a 5.x release, and we can rack up any other breaking changes plan in the mean time.

**Comment by prat0088** [comment]
Any idea when this will happen?

Would aliasing StackExchange Redis 1.2.6 solve the problem?  That's what I'm doing now with my own project that is using 2.x along side MiniProfiler's redis storage.  It's annoying because Visual Studio isn't smart enough to figure out the alias so code completion breaks for StackExchange.Redis.  If we aliased StackExchange.Redis inside MiniProfiler.Providers.Redis then I wonder if it would resolve the issue.  Just thinking aloud since I don't have time to try it out this week.

**Comment by NickCraver** [comment]
We'll need to do this in MiniProfiler v5 for safety's sake - at which point we'll drop < netstandard2.0 or 2.1 support overall. I expect this to happen in the next few months.

**Comment by NickCraver** [comment]
Decided to put this in the 4.2.x release, see #473 for details!

**Comment by Caspeco-MarcusOtterstrom** [comment]
Forgive me if this is the wrong place to ask, but is there a planned release date for 4.2.x? And will it target .NET Standard 2.0? We're looking forward to this dependency change. Right now our solution is to copy the files for `MiniProfiler.Providers.Redis` manually, since we can't install both `StackExchange.Redis.StrongName` and `StackExchange.Redis`.

Thank you! :)

**Comment by NickCraver** [comment]
@Caspeco-MarcusOtterstrom it went up to NuGet this morning, was just finding the time after Stack Overflow dogfooding - 4.2.1 is now on NuGet :)
