### ISSUE TITLE
What is the state of postgresql package?

### ISSUE THREAD

**Issue by mifopen** [MiniProfiler/dotnet#406]
It is the only package published only to MyGet without any older version in NuGet. Why?

**Comment by NickCraver** [comment]
Because I forgot after #369 was merged :( Thanks for the reminder though! Adding a new package is a bit manual (for security reasons). But after that publishing from MyGet to NuGet is trivial - I've uploaded 4.0.180 (latest stable) and 4.1.0-preview18 (latest latest) to NuGet - they'll appear once done validating at https://www.nuget.org/packages/MiniProfiler.Providers.PostgreSql

Thanks for the poke!
