### ISSUE TITLE
MiniProfiler replaces variable name in OPTIMIZE FOR when displaying generated SQL

### ISSUE THREAD

**Issue by RudeySH** [MiniProfiler/dotnet#411]
I have written an `DbCommandInterceptor` that intercepts certain queries and adds the `OPTIMIZE FOR` query hint. Here's an example of the generated SQL after my interceptor has done what it should do:

```
SELECT 
    [Extent1].[AppId] AS [AppId]
    FROM [dbo].[App] AS [Extent1]
    WHERE [Extent1].[AppId] = @p__linq__0
    OPTION (OPTIMIZE FOR (@p__linq__0 = 9999))
```

But when this query is profiled (let's say we use 123 as the value for the parameter), the query is displayed by MiniProfile like so:

```
SELECT 
    [Extent1].[AppId] AS [AppId]
    FROM [dbo].[App] AS [Extent1]
    WHERE [Extent1].[AppId] = 123
    OPTION (OPTIMIZE FOR (123 = 9999))
```

The second occurrence of "@p__linq__0" in the query should not be replaced with the value of the parameter.

**Comment by NickCraver** [comment]
FWIW, I don't recommend using this provider to format the SQL (since it's not really correct - e.g. those queries can and often will behave differently when the values aren't parameters. For example if you have a query parameter that's 5 and it's `@myParam` that _wouldn't_ use a filtered index of `Where Field = 5`. Or choose a different cardinality estimate path and another query plan in general (forced parameterization may hide things here).

Anyway, I suggest using the `SqlServerFormatter`, like this:
```c#
services.AddMiniProfiler(options =>
{
    // ...other config...
    options.SqlFormatter = new StackExchange.Profiling.SqlFormatters.SqlServerFormatter();
});
```
It's much better at this and surfaces the parameters to the top as declare statements. This is both more robust and accurate. The inline formatter is, by nature, pretty stupid. To make it understand any SQL language (remember we support any ADO.NET path here) would be crazy amounts of work, fairly expensive, and drastic overkill...so I argue it's not reasonable to fix for this case :) (happy to discuss! - it's just a _really_ hard problem)

Does the `SqlServerFormatter` sound like it'd solve your issue? For what it's worth, that's what we use at Stack Overflow.

**Comment by RudeySH** [comment]
That solves the issue, thanks!

(I really like the way the `SqlServerFormatter` declares the variables on the top, too.)
