### ISSUE TITLE
How to set color or CSS class by calling customtiming?

### ISSUE THREAD

**Issue by MonkSoul** [MiniProfiler/dotnet#504]
How to set the background color and font?

for example, the program will display the red background by default, but I will manually call customtiming to set the color or CSS class.

**Comment by NickCraver** [comment]
I'm sorry but I'm not really following what's being asked here - can you screenshot or something what piece of UI you're referring to?

**Comment by MonkSoul** [comment]
How to control the display style by program, such as background color?

![bj](https://user-images.githubusercontent.com/22766122/87120242-95b73300-c2b2-11ea-88c1-6674389c787f.png)

**Comment by NickCraver** [comment]
Ah I see - 2 things here:
1. The red background is because there was an error. This is set on the custom timing via the `.Errored` property.
2. The exclamation mark is importance and denotes either a duplicate timing or "warnings" (the error property above)

An example of 1 would look like this:
```cs
using (var timing = profiler.CustomTimingIf("redis", "command that errors", 5))
{
    timing.Errored = true;
    Thread.Sleep(10);
}
```

If you're wanting to change the actual color of them, those are CSS variables [defined here](https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.Shared/ui/includes.less)

**Comment by MonkSoul** [comment]
> Ah I see - 2 things here:
> 
> 1. The red background is because there was an error. This is set on the custom timing via the  property.`.Errored`
> 2. The exclamation mark is importance and denotes either a duplicate timing or "warnings" (the error property above)
> 
> An example of 1 would look like this:
> 
> ```cs
> using (var timing = profiler.CustomTimingIf("redis", "command that errors", 5))
> {
>     timing.Errored = true;
>     Thread.Sleep(10);
> }
> ```
> 
> If you're wanting to change the actual color of them, those are CSS variables [defined here](https://github.com/MiniProfiler/dotnet/blob/main/src/MiniProfiler.Shared/ui/includes.less)

Thinks! 💯 🥇 👍
