### ISSUE TITLE
Samples.Mvc under IISExpress: "Unable to run your project. The "RunCommand" property is not defined."

### ISSUE THREAD

**Issue by reponemec** [MiniProfiler/dotnet#556]
Visual Studio 2019 16.9.4
.csproj:
```
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <OutputType>Library</OutputType>
    <RootNamespace>Samples.Mvc5</RootNamespace>
    <AssemblyName>Samples.Mvc5</AssemblyName>
    <TargetFramework>net462</TargetFramework>
    <UseIISExpress>true</UseIISExpress>
    <OutputPath>bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <PostBuildEvent>
      if not exist "roslyn" md "roslyn"
      xcopy /s /y /q "$(CscToolPath)\*.*" "roslyn"
    </PostBuildEvent>
  </PropertyGroup>
```

After pressing F5 Visual Studio only display following dialog message: _Unable to run your project. The "RunCommand" property is not defined._ and stops executing.

**Comment by NickCraver** [comment]
This generally means you don't have the proper workloads installed in Visual Studio...but I'm also not exactly sure which workloads are needed either (it's in _my_ install, and always has been). If we can identify them, we can add a `.vsconfig` file to the repo root so that it'll prompt others to install anything needed to work here.

**Comment by NickCraver** [comment]
Closing this out to tidy up.
