### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by LeonardoDaLuz** [MiniProfiler/dotnet#596]
https://miniprofiler.com/dotnet/HowTo/ProfileSql

This sample does not work in mysql, and MiniProfiler.Current does'n exists. The "usings" are also missing in the examples, since there are many referring libs it is difficult to guess the "usings":

public static DbConnection GetConnection()
{
    DbConnection connection = new System.Data.SQLite.SQLiteConnection("Data Source=:memory:");
    return new StackExchange.Profiling.Data.ProfiledDbConnection(connection, MiniProfiler.Current); 
}

my mysql version:
public static DbConnection GetConnection()
{
    DbConnection connection = new MySqlConnection(("Data Source=:memory:");
    return new StackExchange.Profiling.Data.ProfiledDbConnection(connection, MiniProfiler.Current);
}
if I use CustomDbProfiler.Current instead MiniProfiler.Current the script runs, but connection won't tracked in profilling sessions on miniprofiler frontend.

**Comment by NickCraver** [comment]
The using here is `using StackExchange.Profiling;` (your IDE will generally suggest the appropriate namespace - that's why few examples have them). The documentation is correct for usage, though we can add the usings to it - I'd like to get you going though, is it working correctly with the using? It's possible you have the wrong package referenced for the platform your on and that's what's confusing.

What are you building for, on which framework target - and which packages are you referencing? Note that the profiler _needs to be started_ before you're passing it into the connection there, otherwise it'll be null and not logging to anything.

**Comment by NickCraver** [comment]
Happy to help further with more info but I hope the above helps! Closing out to tidy up :)
