### ISSUE TITLE
Can not view results-index - MiniProfiler.list is undefined

### ISSUE THREAD

**Issue by sigintarag** [MiniProfiler/dotnet#80]
Feature to access the last 100 profiled requests via ~/mini-profiler-resources/results-index results in a javascript error that MiniProfiler.list is undefined.

Note that on application start Results_List_Authorize is set:

MiniProfiler.Settings.Results_List_Authorize = r => true;

**Comment by evilbloodydemon** [comment]
any feedback on this?

**Comment by fzhenmei** [comment]
+1

**Comment by magicodes** [comment]
i++

**Comment by Strandedpirate** [comment]
bueller... bueller....... .. bueller.....

**Comment by yellis** [comment]
To all who are waiting on this: this feature was built by someone who used to be (but is no longer) active on the project. WIth the upgrade to v3 a while back, something about the refactoring broke this. I spent some time trying to figure out why it isn't working. As you can tell by the lack of progress on this issue, I was not successful. And unfortunately, since this is not something that we really use anymore, I cannot justify spending more time on this right now. So from my perspective, unfortunately, this is an abandoned feature that will not come back...

...however, if someone wants to spend some time on this, get it working and submit the needed changes in a Pull Request, I would be ore than happy to merge that in.

**Comment by digitalpacman** [comment]
+1 ;( I'm gonna see if I can't fix it

**Comment by jakefoster** [comment]
+1

digitalpacman - you will be my hero if you can fix this...

**Comment by gawelczyk** [comment]
+1 same problem
I can see JavaScript error in FF:
TypeError: MiniProfiler.list is undefined results-index:5:0

**Comment by nathangustafson** [comment]
+1

**Comment by ogun** [comment]
I've just committed the fix for this repository and ui repository. Hope it helps...

**Comment by StanleyGoldman** [comment]
Nice, when does the nuget package update?

**Comment by lydonchandra** [comment]
Great work @ogun !! 
results-index is working again for me.

**Comment by ogun** [comment]
Thank you :)

It didn't take so much time exactly because I copied it from the v2. I could say it took nearly one hour...

**Comment by leszekrogowski** [comment]
Great job @ogun!

However, there is still no updated NuGet package. @yellis, do you plan to release NuGet package in the nearest feature?

**Comment by akamud** [comment]
I downloaded the project and built the package, I uploaded the NuGet to a MyGet feed so I can use it in my project, I'm not sure if I'm allowed to share this link (regarding license rights), so if this is ok, I can share it here until we have an official NuGet package updated

**Comment by akamud** [comment]
I downloaded the project and built the package, I uploaded the nupkg to a MyGet feed so I can use it in my project, I'm not sure if I'm allowed to share this link (regarding license rights), so if this is ok, I can share it here until we have an official NuGet package updated

**Comment by yellis** [comment]
This was just included in [nuget 3.2.0.157](https://www.nuget.org/packages/MiniProfiler/3.2.0.157)
